# Generated by Django 3.1.7 on 2021-02-23 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionario',
        ),
    ]
