# Generated by Django 3.1.7 on 2021-02-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0003_auto_20210223_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('funcionarios', models.ManyToManyField(to='funcionario.Funcionario')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
    ]
